/* eslint-disable @typescript-eslint/no-unused-vars */
"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, Copy, Download, Eye, EyeOff, KeyRound, Moon, Plus, Search, ShieldCheck, Sun, Trash2, Upload, X } from "lucide-react";

type Account = { id:string; name:string; issuer:string; secret:string; digits:6|8; period:number; algorithm:"SHA-1"|"SHA-256"|"SHA-512" };
type Token = { code:string; remaining:number };
const STORAGE="secure-authenticator:v1";
function base32Decode(input:string):Uint8Array { const alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"; const clean=input.toUpperCase().replace(/[\s=-]/g,""); let bits=0,value=0; const out:number[]=[]; for(const ch of clean){const idx=alphabet.indexOf(ch);if(idx<0)continue;value=(value<<5)|idx;bits+=5;if(bits>=8){bits-=8;out.push((value>>>bits)&255)}} return new Uint8Array(out); }
function parseOtpUri(uri:string){try{const u=new URL(uri);if(u.protocol!=="otpauth:"||u.hostname!=="totp")return null;const label=decodeURIComponent(u.pathname.replace(/^\/+/,""));const [issuerFromLabel,name]=label.includes(":")?label.split(/:(.*)/,2):["",label];const p=u.searchParams,issuer=p.get("issuer")||issuerFromLabel||"Authenticator",secret=p.get("secret")||"";if(!secret)return null;const alg=(p.get("algorithm")||"SHA1").toUpperCase().replace("-","");return{name:name||"Account",issuer,secret,digits:(p.get("digits")==="8"?8:6) as 6|8,period:Number(p.get("period")||30)||30,algorithm:(alg==="SHA256"?"SHA-256":alg==="SHA512"?"SHA-512":"SHA-1") as Account["algorithm"]};}catch{return null}}
async function makeTotp(a:Account,ts=Date.now()):Promise<Token>{const period=Math.max(1,a.period||30),counter=Math.floor(ts/1000/period),buffer=new ArrayBuffer(8),view=new DataView(buffer);view.setUint32(0,Math.floor(counter/0x100000000));view.setUint32(4,counter>>>0);const key=await crypto.subtle.importKey("raw",new Uint8Array(base32Decode(a.secret)).slice().buffer,{name:"HMAC",hash:a.algorithm},false,["sign"]),sig=new Uint8Array(await crypto.subtle.sign("HMAC",key,buffer)),offset=sig[sig.length-1]&15,bin=((sig[offset]&127)<<24)|((sig[offset+1]&255)<<16)|((sig[offset+2]&255)<<8)|(sig[offset+3]&255),mod=a.digits===8?100000000:1000000;return{code:String(bin%mod).padStart(a.digits,"0"),remaining:period-(Math.floor(ts/1000)%period)}}
const makeId=()=>`${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
export default function Authenticator(){
 const[accounts,setAccounts]=useState<Account[]>([]),[tokens,setTokens]=useState<Record<string,Token>>({}),[query,setQuery]=useState(""),[dark,setDark]=useState(false),[modal,setModal]=useState(false),[showSecrets,setShowSecrets]=useState(false),[notice,setNotice]=useState(""),[form,setForm]=useState({name:"",issuer:"",secret:"",digits:"6",period:"30",algorithm:"SHA-1"});
 useEffect(()=>{try{const r=localStorage.getItem(STORAGE);if(r){const p=JSON.parse(r);if(Array.isArray(p.accounts))setAccounts(p.accounts);if(typeof p.dark==="boolean")setDark(p.dark)}}catch{}},[]); useEffect(()=>{localStorage.setItem(STORAGE,JSON.stringify({accounts,dark}))},[accounts,dark]); useEffect(()=>{document.documentElement.classList.toggle("dark",dark)},[dark]);
 useEffect(()=>{let alive=true;const update=async()=>{const n:Record<string,Token>={};await Promise.all(accounts.map(async a=>{try{n[a.id]=await makeTotp(a)}catch{n[a.id]={code:"------",remaining:a.period}}}));if(alive)setTokens(n)};update();const t=window.setInterval(update,1000);return()=>{alive=false;window.clearInterval(t)}},[accounts]);
 const filtered=useMemo(()=>{const q=query.toLowerCase().trim();return accounts.filter(a=>!q||a.name.toLowerCase().includes(q)||a.issuer.toLowerCase().includes(q))},[accounts,query]); const toast=(m:string)=>{setNotice(m);window.setTimeout(()=>setNotice(""),2200)};
 function add(){const secret=form.secret.replace(/\s+/g,"").toUpperCase();if(!form.name.trim()||!secret)return toast("Enter an account name and secret key.");try{base32Decode(secret);setAccounts(v=>[{id:makeId(),name:form.name.trim(),issuer:form.issuer.trim()||"Authenticator",secret,digits:form.digits==="8"?8:6,period:Math.max(1,Number(form.period)||30),algorithm:form.algorithm as Account["algorithm"]},...v]);setForm({name:"",issuer:"",secret:"",digits:"6",period:"30",algorithm:"SHA-1"});setModal(false);toast("Account added.")}catch{toast("That secret key is not valid.")}}
 function importUri(){const raw=window.prompt("Paste an otpauth:// URI:");if(!raw)return;const p=parseOtpUri(raw.trim());if(!p)return toast("Invalid TOTP URI.");setAccounts(v=>[{...p,id:makeId()},...v]);toast("Account imported.")}
 async function copy(a:Account){const t=tokens[a.id]||await makeTotp(a);await navigator.clipboard.writeText(t.code);toast("Code copied.")}
 function remove(id:string){if(confirm("Remove this account from this browser?")){setAccounts(v=>v.filter(a=>a.id!==id));toast("Account removed.")}}
 function backup(){const blob=new Blob([JSON.stringify({version:1,accounts},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="authenticator-backup.json";a.click();URL.revokeObjectURL(url);toast("Backup exported.")}
 function restore(file:File){const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(String(r.result));if(!Array.isArray(p.accounts))throw 0;const safe=p.accounts.filter((a:Account)=>a&&typeof a.name==="string"&&typeof a.secret==="string").map((a:Account)=>({...a,id:makeId()}));setAccounts(v=>[...safe,...v]);toast(`${safe.length} account(s) imported.`)}catch{toast("Invalid backup file.")}};r.readAsText(file)}
 return <main className="shell"><header className="topbar"><div className="brand"><div className="logo"><ShieldCheck size={24}/></div><div><h1>Secure Authenticator</h1><p>Private TOTP codes in your browser</p></div></div><div className="top-actions"><button className="icon-btn" title="Toggle theme" onClick={()=>setDark(v=>!v)}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button><button className="secondary" onClick={importUri}><KeyRound size={17}/> Import URI</button><button className="primary" onClick={()=>setModal(true)}><Plus size={18}/> Add account</button></div></header>
 <section className="hero"><div><div className="eyebrow"><span className="dot"/> Local-only by default</div><h2>Your codes. <span>On your device.</span></h2><p>Generate standard TOTP 2FA codes without sending your secrets to a server. Works with services that support authenticator apps.</p></div><div className="hero-badge"><ShieldCheck size={22}/><b>No passwords</b><small>Never enter a service password here.</small></div></section>
 <section className="toolbar"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search accounts..."/></div><label className="file-btn"><Upload size={16}/> Restore backup<input type="file" accept="application/json,.json" hidden onChange={e=>e.target.files?.[0]&&restore(e.target.files[0])}/></label><button className="secondary" onClick={backup} disabled={!accounts.length}><Download size={16}/> Backup</button></section>
 {accounts.length===0?<section className="empty"><div className="empty-icon"><KeyRound size={30}/></div><h3>No accounts yet</h3><p>Add a TOTP secret from your authenticator setup screen. You can also import an <code>otpauth://</code> URI.</p><button className="primary" onClick={()=>setModal(true)}><Plus size={18}/> Add your first account</button></section>:<section className="grid">{filtered.map(a=>{const t=tokens[a.id],pct=t?(t.remaining/a.period)*100:0;return <article className="card" key={a.id}><div className="card-head"><div className="account-mark">{(a.issuer||a.name).slice(0,1).toUpperCase()}</div><div className="account-title"><b>{a.name}</b><span>{a.issuer}</span></div><button className="icon-btn danger" title="Remove" onClick={()=>remove(a.id)}><Trash2 size={17}/></button></div><div className="code-wrap"><div className="code">{t?.code?.slice(0,Math.floor(a.digits/2))} {t?.code?.slice(Math.floor(a.digits/2))}</div><div className="timer"><span style={{width:`${pct}%`}}/></div><div className="timer-row"><span>Refreshes in {t?.remaining??a.period}s</span><button onClick={()=>copy(a)}><Copy size={14}/> Copy</button></div></div><div className="meta"><span>{a.digits}-digit</span><span>{a.algorithm}</span><span>{a.period}s</span></div><div className="secret-row"><code>{showSecrets?a.secret:"••••••••••••••••••••"}</code><button className="icon-btn" title={showSecrets?"Hide secrets":"Show secrets"} onClick={()=>setShowSecrets(v=>!v)}>{showSecrets?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></article>})}</section>}
 <footer><span><ShieldCheck size={15}/> Your TOTP secrets stay in this browser's local storage.</span><span>Do not share your secret keys or backup files.</span></footer>{notice&&<div className="toast"><Check size={16}/>{notice}</div>}
 {modal&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setModal(false)}><div className="modal"><div className="modal-head"><div><h3>Add authenticator account</h3><p>Enter the TOTP details provided by the service.</p></div><button className="icon-btn" onClick={()=>setModal(false)}><X size={19}/></button></div><label>Account name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. My Google account"/></label><label>Issuer<input value={form.issuer} onChange={e=>setForm({...form,issuer:e.target.value})} placeholder="e.g. Google"/></label><label>Secret key<input value={form.secret} onChange={e=>setForm({...form,secret:e.target.value})} placeholder="JBSWY3DPEHPK3PXP" autoComplete="off"/></label><div className="two"><label>Digits<select value={form.digits} onChange={e=>setForm({...form,digits:e.target.value})}><option>6</option><option>8</option></select></label><label>Period (seconds)<input type="number" min="1" value={form.period} onChange={e=>setForm({...form,period:e.target.value})}/></label></div><label>Algorithm<select value={form.algorithm} onChange={e=>setForm({...form,algorithm:e.target.value})}><option>SHA-1</option><option>SHA-256</option><option>SHA-512</option></select></label><div className="warning"><b>Security note:</b> Never paste a password, recovery code, or login credential here. Only use the authenticator secret generated by the service.</div><div className="modal-actions"><button className="secondary" onClick={()=>setModal(false)}>Cancel</button><button className="primary" onClick={add}>Add account</button></div></div></div>}</main> }